id: I0D2BB6D3
legacy_id: P008110
ocr_import_info:
  bdrc_scan_id: W27596
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T22:24:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:30:36.905286+00:00'
last_modified: 2022-09-02 15:30:52.459985
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27596
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27596
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་དབང་དཔལ་ཡུལ་བའི་གདན་རབས་ངོ་མཚར་འཆི་མེད་ཡོངས་འདུའི་ལྗོན་པའི་ཕྲེང་བ།
  author: ཚེ་རིང་བླ་མ་འཇམ་དཔལ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7769831292771199
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I4464:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4464
      total_pages: 198
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4464.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7769831292771199
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
