id: P008110
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27596
  title: རྒྱལ་དབང་དཔལ་ཡུལ་བའི་གདན་རབས་ངོ་མཚར་འཆི་མེད་ཡོངས་འདུའི་ལྗོན་པའི་ཕྲེང་བ
  author: ''
  volumes:
    90fa047687664e8981606bf119739133:
      image_group_id: I4464
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
